packages:
  - '*/src'
catalog:
  '@types/node': ^24.9.1
  '@types/seedrandom': ^3.0.8
  '@slidev/cli': ^52.6.0
  '@slidev/client': ^52.6.0
  '@iconify/collections': ^1.0.609
  '@iconify/json': ^2.2.399
  eslint: ^9.38.0
  rimraf: ^6.0.1
  tsx: ^4.20.6
  typescript: ^5.9.3
  unocss: 66.4.0
  vite: ^7.1.12
  seedrandom: ^3.0.5
  vue-router: ^4.6.3
  vue-tsc: ^3.1.2
onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
  - unrs-resolver
